//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrackingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Credentials
    {
        public int UserID { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public string Comment { get; set; }
        public int CredentialID { get; set; }
    
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
